v1.3.0 (#134)
* feat(core): support serverTimestamp in firestore set (#133) - @james-dowell
* fix(ci): remove usage of service account in CI
* feat(ci): add creating of Github release to publish workflow
* feat(ci): add caching of firebase emulator binaries
* chore(deps): update dev dependencies including typescript, eslint and firebase-tools

Co-authored-by: James Dowell <jamesdowell1@gmail.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -25,45 +25,37 @@ jobs:
           node-version: 12
           registry-url: https://registry.npmjs.org/
 
-      - name: Get yarn cache
+      - name: Get cache settings
+        id: cache-settings
+        run: |
+          echo "::set-output name=dir::$(yarn cache dir)"
+          echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
+          
+      - name: Cache Yarn Dependencies
         if: steps.check.outputs.changed == 'true'
-        id: yarn-cache
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-
-      - uses: actions/cache@v1
-        if: steps.check.outputs.changed == 'true'
+        uses: actions/cache@v1
         with:
-          path: ${{ steps.yarn-cache.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
+          path: ${{ steps.cache-settings.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ matrix.app }}-${{ hashFiles('yarn.lock') }}
+
+      - name: Cache Firebase Emulator Binaries
+        if: steps.check.outputs.changed == 'true'
+        uses: actions/cache@v1
+        with:
+          path: ~/.cache/firebase/emulators
+          key: ${{ runner.os }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}
 
       - name: Install Dependencies
         if: steps.check.outputs.changed == 'true'
-        env:
-          CI: true
         run: yarn install --frozen-lockfile
 
       - name: Check For Lint
         if: steps.check.outputs.changed == 'true'
-        env:
-          CI: true
         run: yarn lint
-
-      - name: Expose Test Environment Variables
-        if: steps.check.outputs.changed == 'true'
-        env:
-          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF: ${{ github.ref }}
-        # Generate Service Account file required to prevent credential error (jq used to format)
-        run: |
-          echo "Generating Service Account File..."
-          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
-          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
 
       - name: Run Unit Tests + Coverage
         if: steps.check.outputs.changed == 'true'
         env:
-          CI: true
           CODE_CLIMATE: ${{ secrets.CODE_CLIMATE }}
         run: yarn test:cov
 
@@ -89,23 +81,33 @@ jobs:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
           GITHUB_REF: ${{ github.ref }}
         run: |
-          export GIT_BRANCH=${GITHUB_REF##*/}
-          export PUBLISH_FLAG=$(if [ "$GITHUB_REF" != 'refs/heads/master' ]; then eval echo '--tag $GIT_BRANCH'; else echo ''; fi;)
-          npm publish $PUBLISH_FLAG
+          gitBranch=${GITHUB_REF##*/}
+          packageVersion=$(cat package.json | jq -r '.version')
+          publishFlag=$(if [ "$GITHUB_REF" != 'refs/heads/master' ]; then eval echo '--tag $gitBranch'; else echo ''; fi;)
+          echo "::set-env name=PACKAGE_VERSION::$packageVersion"
+          npm publish $publishFlag
 
       - name: Archive Build Artifact
         if: steps.check.outputs.changed == 'true'
-        uses: actions/upload-artifact@master
+        uses: actions/upload-artifact@v2
         with:
           name: build
           path: lib
 
+      # Upload to codecov.io. Curl used in place of codecov/codecov-action
+      # due to long build time. See https://github.com/codecov/codecov-action/issues/21
       - name: Upload Coverage
         if: steps.check.outputs.changed == 'true'
-        env:
-          CI: true
-          CODE_COV: ${{ secrets.CODE_COV }}
-        # Upload to Code Cover. Curl used in place of codecov/codecov-action
-        # due to long build time. See https://github.com/codecov/codecov-action/issues/21
-        run: curl -s https://codecov.io/bash | bash -s -- -t $CODE_COV
+        run: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
 
+      - name: Create Release
+        if: steps.check.outputs.changed == 'true'
+        id: create_release
+        uses: actions/create-release@latest
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        with:
+          tag_name: v${{ env.PACKAGE_VERSION }}
+          release_name: v${{ env.PACKAGE_VERSION }}
+          draft: false
+          prerelease: github.ref != 'refs/heads/master'
diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -18,37 +18,31 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
-      - name: Get yarn cache
-        id: yarn-cache
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-
-      # Setup dependency caching
-      - uses: actions/cache@v1
+      - name: Get cache settings
+        id: cache-settings
+        run: |
+          echo "::set-output name=dir::$(yarn cache dir)"
+          echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
+          
+      - name: Cache Yarn Dependencies
+        uses: actions/cache@v1
         with:
-          path: ${{ steps.yarn-cache.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
+          path: ${{ steps.cache-settings.outputs.dir }}
+          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ matrix.app }}-${{ hashFiles('yarn.lock') }}
+
+      - name: Cache Firebase Emulator Binaries
+        uses: actions/cache@v1
+        with:
+          path: ~/.cache/firebase/emulators
+          key: ${{ runner.os }}-${{ matrix.node-version }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}
 
       - name: Install Dependencies
-        env:
-          CI: true
         run: yarn install --frozen-lockfile
 
       - name: Check For Lint
         run: yarn lint
 
-      - name: Expose Test Environment Variables
-        env:
-          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF: ${{ github.ref }}
-        # Generate Service Account file required to prevent credential error (jq used to format)
-        run: |
-          echo "Generating Service Account File..."
-          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
-          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
-
       - name: Run Unit Tests + Coverage
-        if: success()
         run: yarn test:cov
 
       - name: Run Build
@@ -65,11 +59,7 @@ jobs:
       - name: Size Check
         run: $(yarn bin)/size-limit
 
+      # Upload to codecov.io. Curl used in place of codecov/codecov-action
+      # due to long build time. See https://github.com/codecov/codecov-action/issues/21
       - name: Upload Coverage
-        if: success()
-        env:
-          CI: true
-          CODE_COV: ${{ secrets.CODE_COV }}
-        # Upload to codecov.io. Curl used in place of codecov/codecov-action
-        # due to long build time. See https://github.com/codecov/codecov-action/issues/21
-        run: curl -s https://codecov.io/bash | bash -s -- -t $CODE_COV
+        run: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
